# Generated by Django 3.2.4 on 2024-03-11 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20240311_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=254)),
                ('Mobno', models.CharField(max_length=10)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
